{
 "title": "nginx",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_request_status, host)"
   },
   {
    "name": "tag",
    "label": "Tag",
    "query": "label_values(nginx_request_status, tag)"
   }
  ]
 },
 "panels": [
  {
   "title": "request_status_ranges",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_request_status_ranges{host=\"$host\",tag=\"$tag\"}[1m])"
    }
   ]
  },
  {
   "title": "request_status_ranges (500-599)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_request_status_ranges{host=\"$host\",tag=\"$tag\",range=\"500-599\"}[1m])"
    }
   ]
  },
  {
   "title": "request time (1m average)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_request_time_sum{host=\"$host\",tag=\"$tag\"}[1m]) / delta(nginx_request_time_count{host=\"$host\",tag=\"$tag\"}[1m])"
    }
   ]
  },
  {
   "title": "request time (5m average)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_request_time_sum{host=\"$host\",tag=\"$tag\"}[5m]) / delta(nginx_request_time_count{host=\"$host\",tag=\"$tag\"}[5m])"
    }
   ]
  },
  {
   "title": "request time (15m average)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_request_time_sum{host=\"$host\",tag=\"$tag\"}[15m]) / delta(nginx_request_time_count{host=\"$host\",tag=\"$tag\"}[15m])"
    }
   ]
  }
 ]
}